if(NOT DEFINED GCOV OR NOT DEFINED OBJECT_DIR OR NOT DEFINED GCOV_INPUT OR NOT DEFINED SOURCE_FILES)
  message(FATAL_ERROR "GCOV, OBJECT_DIR, GCOV_INPUT, and SOURCE_FILES are required")
endif()

execute_process(
  COMMAND "${GCOV}" -b "${GCOV_INPUT}"
  WORKING_DIRECTORY "${OBJECT_DIR}"
  RESULT_VARIABLE gcov_result
  OUTPUT_VARIABLE gcov_output
  ERROR_VARIABLE gcov_error)
if(NOT gcov_result EQUAL 0)
  message(FATAL_ERROR "gcov failed: ${gcov_error}")
endif()

string(REPLACE "," ";" report_files "${SOURCE_FILES}")
set(lines_total 0)
set(lines_hit 0)
set(branches_total 0)
set(branches_hit 0)
foreach(report_file IN LISTS report_files)
  set(report_path "${OBJECT_DIR}/${report_file}")
  if(NOT EXISTS "${report_path}")
    message(FATAL_ERROR "Expected coverage report was not generated: ${report_path}")
  endif()
  file(STRINGS "${report_path}" report_lines)
  foreach(report_line IN LISTS report_lines)
    if(report_line MATCHES "^[ 	]*([0-9]+|#####):")
      math(EXPR lines_total "${lines_total} + 1")
      if(NOT report_line MATCHES "^[ 	]*#####:")
        math(EXPR lines_hit "${lines_hit} + 1")
      endif()
    endif()
    if(report_line MATCHES "^[ 	]*branch[ 	]+[0-9]+ (taken [0-9]+%|never executed)")
      math(EXPR branches_total "${branches_total} + 1")
      if(report_line MATCHES "taken [0-9]+%")
        math(EXPR branches_hit "${branches_hit} + 1")
      endif()
    endif()
  endforeach()
endforeach()

if(lines_total EQUAL 0 OR branches_total EQUAL 0)
  message(FATAL_ERROR "Coverage reports contained no executable lines or branches")
endif()
math(EXPR line_percent "100 * ${lines_hit} / ${lines_total}")
math(EXPR branch_percent "100 * ${branches_hit} / ${branches_total}")
message(STATUS "Scoped coverage: lines=${line_percent}% branches=${branch_percent}% (${SOURCE_FILES})")

if(DEFINED EXPECT_LINE_BELOW)
  if(line_percent LESS EXPECT_LINE_BELOW)
    message(FATAL_ERROR "Controlled fixture correctly falls below ${EXPECT_LINE_BELOW}% lines: ${line_percent}%")
  endif()
  message(FATAL_ERROR "Controlled fixture unexpectedly met ${EXPECT_LINE_BELOW}% lines: ${line_percent}%")
endif()

if(line_percent LESS LINE_MINIMUM OR branch_percent LESS BRANCH_MINIMUM)
  message(FATAL_ERROR "Coverage below gate: need ${LINE_MINIMUM}% lines / ${BRANCH_MINIMUM}% branches")
endif()
foreach(helper_file IN LISTS report_files)
  # The scoped helper reports are individually ratcheted at 85% lines.
  file(STRINGS "${OBJECT_DIR}/${helper_file}" helper_lines)
  set(helper_total 0)
  set(helper_hit 0)
  foreach(helper_line IN LISTS helper_lines)
    if(helper_line MATCHES "^[ 	]*([0-9]+|#####):")
      math(EXPR helper_total "${helper_total} + 1")
      if(NOT helper_line MATCHES "^[ 	]*#####:")
        math(EXPR helper_hit "${helper_hit} + 1")
      endif()
    endif()
  endforeach()
  math(EXPR helper_percent "100 * ${helper_hit} / ${helper_total}")
  if(helper_percent LESS HELPER_LINE_MINIMUM)
    message(FATAL_ERROR "${helper_file} below ${HELPER_LINE_MINIMUM}% helper line gate: ${helper_percent}%")
  endif()
endforeach()
